### PR TITLE
Add support for Dockerfile deploy

### PR DESCRIPTION
**Pull request by shime**
This PR adds support for deploying directly from Dockerfile, without using the private registry.

### CODE REVIEW

**Comment by UserNotFound** [comment]
Hi @shime, thanks for the contribution. Can you clarify how this change is used in your workflow? [Deploying to Aptible from a Dockerfile](https://deploy-docs.aptible.com/docs/dockerfile-deploy) requires you to `git push` your code to our server, which can already trigger a deploy if you `git push` your code to the "master" branch on the Aptible remote server.  

From my understanding, you must already be using some automation (another Github Action?) to push the code _before_ this action runs the `aptible deploy` command you added, so at face value this change looks redundant but I'm hoping you can clarify further?

**Comment by shime** [comment]
Hi Alex, unless I'm missing something, I think `aptible deploy` will deploy from a Dockerfile when no private registry arguments were given. I've successfully deployed an app from a Dockerfile like that. But, it's true that we have since moved to `git push` deploy, because we don't want to store Aptible credentials in Github secrets.

**Comment by UserNotFound** [comment]
True, an `aptible deploy` command will trigger a Deploy operation. However, it's just going to build the exact same Dockerfile along with the same code you already pushed via Git.  Consider a typical Dockerfile for a very basic Ruby app:

```
FROM ruby:2.4

RUN apt-get update \
 && apt-get -y install build-essential libpq-dev \
 && rm -rf /var/lib/apt/lists/*

ADD Gemfile /app/
ADD Gemfile.lock /app/
WORKDIR /app
RUN bundle install

ADD . /app

RUN set -a \
 && . ./.aptible.env \
 && bundle exec rake assets:precompile

EXPOSE 3000

CMD ["bundle", "exec", "rails", "s", "-b", "0.0.0.0", "-p", "3000"]
```

You might end up with slight differences if the parent `ruby:2.4` images changes, or a different version of `libpq-dev`, but without pushing changes to Gemfile.lock or the codebase in the root of the repository, no changes to the Ruby application itself on Aptible will be made just by running `aptible deploy` - you need to `git push` your latest code changes before they can be deployed.

**Comment by shime** [comment]
Got it, thanks.

**Pull request closed without merging**
